# Generated by Django 4.1.4 on 2023-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='slug',
            field=models.TextField(default='product'),
        ),
    ]
